package com.knowarth.portlets.themepersonalizer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the AvailablePersonalizedTheme service. Represents a row in the &quot;KNOWARTH_AvailablePersonalizedTheme&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.knowarth.portlets.themepersonalizer.model.impl.AvailablePersonalizedThemeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.knowarth.portlets.themepersonalizer.model.impl.AvailablePersonalizedThemeImpl}.
 * </p>
 *
 * @author Samir Bhatt
 * @see AvailablePersonalizedTheme
 * @see com.knowarth.portlets.themepersonalizer.model.impl.AvailablePersonalizedThemeImpl
 * @see com.knowarth.portlets.themepersonalizer.model.impl.AvailablePersonalizedThemeModelImpl
 * @generated
 */
public interface AvailablePersonalizedThemeModel extends BaseModel<AvailablePersonalizedTheme> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a available personalized theme model instance should use the {@link AvailablePersonalizedTheme} interface instead.
     */

    /**
     * Returns the primary key of this available personalized theme.
     *
     * @return the primary key of this available personalized theme
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this available personalized theme.
     *
     * @param primaryKey the primary key of this available personalized theme
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the ID of this available personalized theme.
     *
     * @return the ID of this available personalized theme
     */
    public long getId();

    /**
     * Sets the ID of this available personalized theme.
     *
     * @param id the ID of this available personalized theme
     */
    public void setId(long id);

    /**
     * Returns the company ID of this available personalized theme.
     *
     * @return the company ID of this available personalized theme
     */
    public long getCompanyId();

    /**
     * Sets the company ID of this available personalized theme.
     *
     * @param companyId the company ID of this available personalized theme
     */
    public void setCompanyId(long companyId);

    /**
     * Returns the theme ID of this available personalized theme.
     *
     * @return the theme ID of this available personalized theme
     */
    @AutoEscape
    public String getThemeId();

    /**
     * Sets the theme ID of this available personalized theme.
     *
     * @param themeId the theme ID of this available personalized theme
     */
    public void setThemeId(String themeId);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(AvailablePersonalizedTheme availablePersonalizedTheme);

    @Override
    public int hashCode();

    @Override
    public CacheModel<AvailablePersonalizedTheme> toCacheModel();

    @Override
    public AvailablePersonalizedTheme toEscapedModel();

    @Override
    public AvailablePersonalizedTheme toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
