/**
 * Copyright (c) 2014 KNOWARTH Technologies Pvt. Ltd. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */
package com.knowarth.portlets.themepersonalizer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the AvailablePersonalizedTheme service. Represents a row in the &quot;KNOWARTH_AvailablePersonalizedTheme&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.knowarth.portlets.themepersonalizer.model.impl.AvailablePersonalizedThemeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.knowarth.portlets.themepersonalizer.model.impl.AvailablePersonalizedThemeImpl}.
 * </p>
 *
 * @author Samir Bhatt
 * @see AvailablePersonalizedTheme
 * @see com.knowarth.portlets.themepersonalizer.model.impl.AvailablePersonalizedThemeImpl
 * @see com.knowarth.portlets.themepersonalizer.model.impl.AvailablePersonalizedThemeModelImpl
 * @generated
 */
public interface AvailablePersonalizedThemeModel extends BaseModel<AvailablePersonalizedTheme> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a available personalized theme model instance should use the {@link AvailablePersonalizedTheme} interface instead.
     */

    /**
     * Returns the primary key of this available personalized theme.
     *
     * @return the primary key of this available personalized theme
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this available personalized theme.
     *
     * @param primaryKey the primary key of this available personalized theme
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the ID of this available personalized theme.
     *
     * @return the ID of this available personalized theme
     */
    public long getId();

    /**
     * Sets the ID of this available personalized theme.
     *
     * @param id the ID of this available personalized theme
     */
    public void setId(long id);

    /**
     * Returns the company ID of this available personalized theme.
     *
     * @return the company ID of this available personalized theme
     */
    public long getCompanyId();

    /**
     * Sets the company ID of this available personalized theme.
     *
     * @param companyId the company ID of this available personalized theme
     */
    public void setCompanyId(long companyId);

    /**
     * Returns the theme ID of this available personalized theme.
     *
     * @return the theme ID of this available personalized theme
     */
    @AutoEscape
    public String getThemeId();

    /**
     * Sets the theme ID of this available personalized theme.
     *
     * @param themeId the theme ID of this available personalized theme
     */
    public void setThemeId(String themeId);

    public boolean isNew();

    public void setNew(boolean n);

    public boolean isCachedModel();

    public void setCachedModel(boolean cachedModel);

    public boolean isEscapedModel();

    public Serializable getPrimaryKeyObj();

    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    public ExpandoBridge getExpandoBridge();

    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    public Object clone();

    public int compareTo(AvailablePersonalizedTheme availablePersonalizedTheme);

    public int hashCode();

    public CacheModel<AvailablePersonalizedTheme> toCacheModel();

    public AvailablePersonalizedTheme toEscapedModel();

    public AvailablePersonalizedTheme toUnescapedModel();

    public String toString();

    public String toXmlString();
}
