/**
 * Copyright (c) 2014 KNOWARTH Technologies Pvt. Ltd. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */
package com.knowarth.portlets.themepersonalizer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the UserPersonalizedTheme service. Represents a row in the &quot;KNOWARTH_UserPersonalizedTheme&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.knowarth.portlets.themepersonalizer.model.impl.UserPersonalizedThemeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.knowarth.portlets.themepersonalizer.model.impl.UserPersonalizedThemeImpl}.
 * </p>
 *
 * @author Samir Bhatt
 * @see UserPersonalizedTheme
 * @see com.knowarth.portlets.themepersonalizer.model.impl.UserPersonalizedThemeImpl
 * @see com.knowarth.portlets.themepersonalizer.model.impl.UserPersonalizedThemeModelImpl
 * @generated
 */
public interface UserPersonalizedThemeModel extends BaseModel<UserPersonalizedTheme> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a user personalized theme model instance should use the {@link UserPersonalizedTheme} interface instead.
     */

    /**
     * Returns the primary key of this user personalized theme.
     *
     * @return the primary key of this user personalized theme
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this user personalized theme.
     *
     * @param primaryKey the primary key of this user personalized theme
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the ID of this user personalized theme.
     *
     * @return the ID of this user personalized theme
     */
    public long getId();

    /**
     * Sets the ID of this user personalized theme.
     *
     * @param id the ID of this user personalized theme
     */
    public void setId(long id);

    /**
     * Returns the user ID of this user personalized theme.
     *
     * @return the user ID of this user personalized theme
     */
    public long getUserId();

    /**
     * Sets the user ID of this user personalized theme.
     *
     * @param userId the user ID of this user personalized theme
     */
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this user personalized theme.
     *
     * @return the user uuid of this user personalized theme
     * @throws SystemException if a system exception occurred
     */
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this user personalized theme.
     *
     * @param userUuid the user uuid of this user personalized theme
     */
    public void setUserUuid(String userUuid);

    /**
     * Returns the layout ID of this user personalized theme.
     *
     * @return the layout ID of this user personalized theme
     */
    public long getLayoutId();

    /**
     * Sets the layout ID of this user personalized theme.
     *
     * @param layoutId the layout ID of this user personalized theme
     */
    public void setLayoutId(long layoutId);

    /**
     * Returns the theme ID of this user personalized theme.
     *
     * @return the theme ID of this user personalized theme
     */
    @AutoEscape
    public String getThemeId();

    /**
     * Sets the theme ID of this user personalized theme.
     *
     * @param themeId the theme ID of this user personalized theme
     */
    public void setThemeId(String themeId);

    /**
     * Returns the color scheme ID of this user personalized theme.
     *
     * @return the color scheme ID of this user personalized theme
     */
    @AutoEscape
    public String getColorSchemeId();

    /**
     * Sets the color scheme ID of this user personalized theme.
     *
     * @param colorSchemeId the color scheme ID of this user personalized theme
     */
    public void setColorSchemeId(String colorSchemeId);

    /**
     * Returns the apply for all pages of this user personalized theme.
     *
     * @return the apply for all pages of this user personalized theme
     */
    public boolean getApplyForAllPages();

    /**
     * Returns <code>true</code> if this user personalized theme is apply for all pages.
     *
     * @return <code>true</code> if this user personalized theme is apply for all pages; <code>false</code> otherwise
     */
    public boolean isApplyForAllPages();

    /**
     * Sets whether this user personalized theme is apply for all pages.
     *
     * @param applyForAllPages the apply for all pages of this user personalized theme
     */
    public void setApplyForAllPages(boolean applyForAllPages);

    public boolean isNew();

    public void setNew(boolean n);

    public boolean isCachedModel();

    public void setCachedModel(boolean cachedModel);

    public boolean isEscapedModel();

    public Serializable getPrimaryKeyObj();

    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    public ExpandoBridge getExpandoBridge();

    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    public Object clone();

    public int compareTo(UserPersonalizedTheme userPersonalizedTheme);

    public int hashCode();

    public CacheModel<UserPersonalizedTheme> toCacheModel();

    public UserPersonalizedTheme toEscapedModel();

    public UserPersonalizedTheme toUnescapedModel();

    public String toString();

    public String toXmlString();
}
