package com.knowarth.portlets.themepersonalizer.model.impl;

import com.knowarth.portlets.themepersonalizer.model.AvailablePersonalizedTheme;
import com.knowarth.portlets.themepersonalizer.service.AvailablePersonalizedThemeLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the AvailablePersonalizedTheme service. Represents a row in the &quot;KNOWARTH_AvailablePersonalizedTheme&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AvailablePersonalizedThemeImpl}.
 * </p>
 *
 * @author Samir Bhatt
 * @see AvailablePersonalizedThemeImpl
 * @see com.knowarth.portlets.themepersonalizer.model.AvailablePersonalizedTheme
 * @generated
 */
public abstract class AvailablePersonalizedThemeBaseImpl
    extends AvailablePersonalizedThemeModelImpl
    implements AvailablePersonalizedTheme {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a available personalized theme model instance should use the {@link AvailablePersonalizedTheme} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            AvailablePersonalizedThemeLocalServiceUtil.addAvailablePersonalizedTheme(this);
        } else {
            AvailablePersonalizedThemeLocalServiceUtil.updateAvailablePersonalizedTheme(this);
        }
    }
}
